<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script>
        document.addEventListener("DOMContentLoaded",()=>{

            try {
                console.log("예외가 발생할 가능성이 있는 코드")
            } catch (error) {
                console.log("예외가 발생할 때 실행할 코드")
            } finally{
                console.log("무조건적으로 실행할 코드")
            }


            try {
                console.log("예외가 발생할 가능성이 있는 코드")
            } catch (error) {
                console.log("예외가 발생할 때 실행할 코드")
            }
            console.log("무조건적으로 실행할 코드")
            // 위와같이 써도 의미가 동일하다.

            // finally가 의미를 가지기 위해선 다음과 같이 사용하도록 한다.

            console.log("----------구분선----------")

            const 예 = ()=>{
                try {
                    console.log("예외 발생 가능성 코드")
                    return
                } catch (error) {
                    console.log("예외 발생 코드")
                } 
                console.log("무조건적으로 실행할 코드")
            }

            예();
            

            const 예2 = ()=>{
                try {
                    console.log("예외 발생 가능성 코드")
                    return
                } catch (error) {
                    console.log("예외 발생 코드")
                } 
                finally{
                    console.log("무조건적으로 실행할 코드")
                }
            }

            예2();
            

            // 보통 예외처리를 하는 경우는
            // 1. 다른 사람이 강제로 발생시킨 예외를 처리하는 경우
            // 2. 없는 속성에 접근해서 활용하는 경우

            // 1번째 경우로
            // 예로 원의 둘레를 구하는 함수를 만들어 살펴본다면
            const getPerimeter = (r) =>{
                // 2. 따라서 강제로 예외를 발생시켜야 할 필요가 있음.
                if(r<0){
                    throw "길이는 음수가 될 수 없습니다."
                }
                // 3. 위와 같이 예외를 강제로 발생시킨다.

                const pi = 3.14;
                return 2*pi*r;
            }

            console.log(getPerimeter(-10))
            // 음수를 넣었을 경우,
            // 1. 나중에 문제가 생길수 있는 잠재적 위험이 존재함.
            console.log("정상적으로 완료되었습니다.")
            // 4. 예외가 발생하여 위 로그는 도출되지않게 된다.
            
        })
    </script>
</head>
<body>
    
</body>
</html>